global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "backend_monitoring"
    static_configs:
      - targets: ["localhost:8000"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
